---
title: "ACP proteome"
geometry: margin=1cm
numbersections: true
output:
  
  
  html_document: 
    
    toc: true
    toc_depth: 5
    theme: "yeti"
    highlight: zenburn
    code_folding: show
  fig_caption: true
  keep_tex: true
editor_options: 
  
  chunk_output_type: console
---


```{r setup, include=FALSE}

library(knitr)

options(width = 300)
options(encoding = 'UTF-8')

knitr::opts_chunk$set(
  fig.width = 7,
  fig.height = 5,
  fig.align = "center",
  fig.show="asis",
  size = "tiny",
  include = TRUE,
  echo = TRUE,
  eval = TRUE,
  warning = FALSE,
  message = FALSE,
  results="asis"
  )

```


# Chargement des librairies pour la session

```{r}

library(knitr)

library(FactoMineR)

library(factoextra)

```


# Importer les données

```{r}

table1<-read.table("C:/Users/Gardette/Documents/APT/2A/Big Data/Proteome/proteome_Ath.csv", sep=";", dec=".", header=T,row.names=1)

```


# Ajout des donnees qualitatives de description des echantillons

```{r}

temperature<-factor(rep(c("Low","Medium","Elevated"),each=3),levels=c("Low","Medium","Elevated"))

table2<-cbind.data.frame(temperature,table1)

```


# analyse factorielle ACP

```{r}

res_pca<-PCA(table2, graph=F,quali.sup=1)

```


# Histogramme des valeurs propres


```{r}

fviz_eig(res_pca, addlabels = TRUE, ylim = c(0, 50))

```


# Nuage des individus

```{r}

# axe 1+2

fviz_ellipses(res_pca,axes=c(1,2),habillage="temperature",palette=c("blue","darkgreen","orange"))

# axe 1+3

fviz_ellipses(res_pca,axes=c(1,3),habillage="temperature",palette=c("blue","darkgreen","orange"))

```


# Nuage des variables

```{r}

## toutes variables

fviz_pca_var(res_pca)

## selection des 50 variables les plus fortes avec coloration selon contribution

# axe 1+2

fviz_pca_var(
  res_pca,
  axes = c(1, 2),
  col.var = "contrib",
  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
  select.var = list(contrib = 50)
)

# axe 1+3

fviz_pca_var(
  res_pca,
  axes = c(1, 3),
  col.var = "contrib",
  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
  select.var = list(contrib = 50)
)


```


# BIPLOT : individus + variables

```{r}

# axe 1+2

fviz_pca_biplot (
  res_pca,
  axes = c(1, 2),
  col.ind = table2$temperature,
  palette = c("blue", "darkgreen", "orange"),
  addEllipses = TRUE,
  ellipse.type = "confidence",
  label = "all",
  col.var = "black",
  select.var = list(contrib = 50),
  arrowsize = 0.2,
  labelsize = 2,
  repel = FALSE,
  legend.title = "temperature"
)

# axe 1+3

fviz_pca_biplot (
  res_pca,
  axes = c(1, 3),
  col.ind = table2$temperature,
  palette = c("blue", "darkgreen", "orange"),
  addEllipses = TRUE,
  ellipse.type = "confidence",
  label = "all",
  col.var = "black",
  select.var = list(contrib = 50),
  arrowsize = 0.2,
  labelsize = 2,
  repel = FALSE,
  legend.title = "temperature"
)


```


# Analyse de l'ACP : 

## Les individus

```{r}

ind <- get_pca_ind(res_pca)

print(ind)

# coordonnees des individus sur les axes

kable(round(ind$coord,2))

# contributions des individus aux axes

kable(round(ind$contrib,2))


write.table(round(ind$coord,2),"acp_proteome_coord_indiv.csv",append=FALSE,sep=";",dec=".",row.names=TRUE,col.names=NA)

```

## Les variables

```{r}

var <- get_pca_var(res_pca)

print(var)

# contributions des variables aux axes

kable(head(round(var$contrib,2),10))

# correlations des variables aux axes

kable(head(round(var$cor,2),10))


write.table(round(var$cor,2),"acp_proteome_correlations_variables.csv",append=FALSE,sep=";",dec=".",row.names=TRUE,col.names=NA)

```


## Filtrage et regroupement des variables

```{r}

# on se base sur les valeurs de correlations aux axes
# en ne gardant que les |cor|>= 0.8

# axe 1 +

tab_var_acp1<-var$cor[order(var$cor[,1],decreasing = TRUE),]

groupe1 <- tab_var_acp1[which(tab_var_acp1[,1]>= 0.8),]

# top 10

kable(head(round(groupe1,2),10))

write.table(round(groupe1,2),"acp_proteome_groupe1.csv",dec=".",sep=";",append=F,row.names=T,col.names=NA)



# axe 1 - 

tab_var_acp2<-var$cor[order(var$cor[,1],decreasing = FALSE),]

groupe2 <- tab_var_acp2[which(tab_var_acp2[,1]<= -0.8),]

# top 10

kable(head(round(groupe2,2),10))

write.table(round(groupe2,2),"acp_proteome_groupe2.csv",dec=".",sep=";",append=F,row.names=T,col.names=NA)



# axe 2 +

tab_var_acp3<-var$cor[order(var$cor[,2],decreasing = TRUE),]

groupe3 <- tab_var_acp3[which(tab_var_acp3[,2]>= 0.8),]

# top 10

kable(head(round(groupe3,2),10))

write.table(round(groupe3,2),"acp_proteome_groupe3.csv",dec=".",sep=";",append=F,row.names=T,col.names=NA)



# axe 2 -

tab_var_acp4<-var$cor[order(var$cor[,2],decreasing = FALSE),]

groupe4 <- tab_var_acp4[which(tab_var_acp4[,2]<= -0.8),]

# top 10

kable(head(round(groupe4,2),10))

write.table(round(groupe4,2),"acp_proteome_groupe4.csv",dec=".",sep=";",append=F,row.names=T,col.names=NA)

```
